import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useMemo, useState } from "react";
import { PanelTitle } from "../../components/ui/PanelTitle.js";

const WOW_CLASSES=["DeathKnight","DemonHunter","Druid","Evoker","Hunter","Mage","Monk","Paladin","Priest","Rogue","Shaman","Warlock","Warrior"];
const CLASS_LABELS={DeathKnight:"Death Knight",DemonHunter:"Demon Hunter"};
const roleLabel=role=>role==="HEAL"?"HEAL":role==="TANK"?"TANK":"DPS";
const classKey=value=>String(value||"").replace(/[^a-z0-9]/gi,"").toLowerCase();
const displayClass=value=>CLASS_LABELS[value]||value||"Unknown";
const output=p=>p?.role==="HEAL"?`${Math.round(Number(p?.bestPull?.hps)||0).toLocaleString()} HPS`:`${Math.round(Number(p?.bestPull?.dps)||0).toLocaleString()} DPS`;
const reliabilityValue=p=>{const raw=p?.reliability?.value;if(raw===null||raw===undefined||raw==="")return null;const n=Number(raw);return Number.isFinite(n)?Math.round(n):null;};
const reliabilityMeta=p=>reliabilityValue(p)==null?"PENDING":(p?.reliability?.confidence?`${String(p.reliability.confidence).toUpperCase()} CONF.`:"CALCULATED");
const wowheadHref=(ref,fallback)=>ref?.url||`https://www.wowhead.com/search?q=${encodeURIComponent(fallback)}`;
const cleanTalentName=value=>{const s=String(value??"").trim();return s&&!/^(?:spell\s+(?:null|undefined)|null|undefined|node\s+\d+|entry\s+\d+)$/i.test(s)?s:"";};
const hasResolvedTalent=t=>Boolean(cleanTalentName(t?.name))||(Number.isFinite(Number(t?.spellId))&&Number(t.spellId)>0);

function WowheadLink({ref,label}){return jsx("a",{className:"wowhead-link",href:wowheadHref(ref,label),target:"_blank",rel:"noreferrer noopener",...(ref?.dataWowhead?{"data-wowhead":ref.dataWowhead}:{}),children:label});}
function CharacterDetail({player}){
  const gear=Array.isArray(player?.character?.gear)?player.character.gear:[];
  const talents=Array.isArray(player?.character?.talents)?player.character.talents:[];
  const resolvedTalents=talents.filter(hasResolvedTalent);
  useEffect(()=>{queueMicrotask(()=>{try{if(window.WH?.Tooltips?.refreshLinks)window.WH.Tooltips.refreshLinks();else if(window.$WowheadPower?.refreshLinks)window.$WowheadPower.refreshLinks();}catch{}});},[player?.actorId]);
  return jsxs("div",{className:"crt-detail",children:[
    jsxs("div",{children:[jsx("h4",{children:"EQUIPMENT · BEST PULL COMBATANT INFO"}),gear.length?jsx("div",{className:"crt-chips gear-list",children:gear.map((item,index)=>jsxs("span",{className:"crt-data-chip gear-chip",children:[jsx("small",{children:item.slot||"Item"}),jsx(WowheadLink,{ref:item.wowhead,label:item.name||`Item #${item.id??"?"}`}),jsx("em",{children:item.itemLevel?`ilvl ${item.itemLevel}`:""})]},`${item.slotId||item.id||index}-${index}`))}):jsx("div",{className:"crt-chips",children:jsx("p",{children:"WCL did not expose normalized gear for this player in the selected CombatantInfo slice."})})]}),
    jsxs("div",{children:[jsx("h4",{children:"TALENTS · BEST PULL BUILD"}),player?.character?.talentImportCode?jsx("div",{className:"crt-chips talents",children:jsxs("span",{className:"crt-data-chip talent-chip talent-build-link",children:[jsx("a",{className:"wowhead-link",target:"_blank",rel:"noreferrer noopener",href:player.character.talentWowheadUrl||`https://www.wowhead.com/talent-calc/blizzard/${encodeURIComponent(player.character.talentImportCode)}`,children:"Open exact talent build on Wowhead"}),jsx("em",{children:"WCL talent import code"})]})}):resolvedTalents.length?jsx("div",{className:"crt-chips talents",children:resolvedTalents.map((t,index)=>jsxs("span",{className:"crt-data-chip talent-chip",children:[jsx(WowheadLink,{ref:t.wowhead,label:cleanTalentName(t.name)||`Spell ${Number(t.spellId)}`}),jsx("em",{children:t.rank!=null?`rank ${t.rank}`:""})]},`${t.spellId||t.entryId||index}-${index}`))}):jsx("div",{className:"crt-chips talents",children:jsx("p",{children:talents.length?"WCL exposed only opaque trait node IDs for this pull. They are hidden until a canonical talent import code or named spell is available.":"Talent data is not present in the selected pull."})})]})
  ]});
}

export function RosterIntelligence({players=[],profileCoverage=null}){
  const [expanded,setExpanded]=useState(null);
  const sorted=useMemo(()=>{const roleRank={TANK:0,HEAL:1,DPS:2};return players.slice().sort((a,b)=>(roleRank[a.role]??9)-(roleRank[b.role]??9)||String(a.className).localeCompare(String(b.className))||String(a.name).localeCompare(String(b.name)));},[players]);
  if(!players.length)return null;
  const counts={};for(const p of players){const key=classKey(p.className);if(key)counts[key]=(counts[key]||0)+1;}const missing=WOW_CLASSES.filter(c=>!counts[classKey(c)]).map(displayClass);const ilvls=players.map(p=>Number(p.itemLevel)).filter(Number.isFinite);const avgIlvl=ilvls.length?ilvls.reduce((a,b)=>a+b,0)/ilvls.length:null;
  const resolvedProfiles=players.filter(p=>Boolean(p?.character?.talentImportCode)||(p?.character?.talents||[]).some(hasResolvedTalent)).length;
  const summary=[["RAIDERS",players.length],["CLASSES",`${Object.keys(counts).length}/${WOW_CLASSES.length}`],["AVG ILVL",avgIlvl==null?"—":avgIlvl.toFixed(1)],["MISSING",missing.length?missing.join(", "):"None"],["GEAR DATA",profileCoverage?`${profileCoverage.withGear}/${profileCoverage.roster}`:"—"],["TALENTS RESOLVED",`${resolvedProfiles}/${players.length}`]];
  return jsxs("article",{className:"panel roster-intelligence-panel",children:[jsx(PanelTitle,{id:"04",title:"Roster intelligence",sub:"Real WCL character facts · item links/tooltips by Wowhead · Reliability shared with Players"}),jsx("div",{className:"roster-intel-summary",children:summary.map(([label,value])=>jsxs("div",{children:[jsx("label",{children:label}),jsx("b",{children:String(value)})]},label))}),jsxs("div",{className:"composition-roster-table",children:[jsx("div",{className:"crt-head",children:["PLAYER","CLASS / SPEC","ROLE","ILVL","GEAR","TALENTS","OUTPUT","RELIABILITY"].map(label=>jsx("span",{children:label},label))}),sorted.map(p=>{const enc=p.encounter||{},gearCount=Number(p?.character?.gearCount)||0,talentCount=Number(p?.character?.talentCount)||0,resolvedTalentCount=(p?.character?.talents||[]).filter(hasResolvedTalent).length,hasTalentImport=Boolean(p?.character?.talentImportCode),actorKey=p.actorId??p.name,isExpanded=expanded===actorKey;return jsxs("div",{className:`crt-row${isExpanded?" expanded":""}`,children:[jsxs("button",{type:"button",className:"crt-main",onClick:()=>setExpanded(isExpanded?null:actorKey),children:[jsxs("span",{className:"crt-player",children:[jsx("i",{children:String(p.name||"?")[0]}),jsxs("span",{children:[jsx("b",{children:p.name}),jsx("small",{children:`${enc.firstDeaths??0} first deaths · ${enc.interrupts??0} interrupts`})]})]}),jsxs("span",{children:[jsx("b",{children:displayClass(p.className)}),jsx("small",{children:p.spec||"Unknown spec"})]}),jsx("span",{className:`crt-role ${String(p.role||"").toLowerCase()}`,children:roleLabel(p.role)}),jsx("b",{children:p.itemLevel??"—"}),jsxs("span",{children:[jsx("b",{children:gearCount?`${gearCount} equipped`:"—"}),jsx("small",{children:gearCount?`WCL character ilvl ${p.itemLevel??"—"}`:"CombatantInfo pending"})]}),jsxs("span",{children:[jsx("b",{children:hasTalentImport?"Exact build":resolvedTalentCount?`${resolvedTalentCount} resolved`:"—"}),jsx("small",{children:hasTalentImport?"WCL import code · Wowhead":resolvedTalentCount?"Named talents from WCL/Wowhead":talentCount?"Raw node IDs hidden":"CombatantInfo pending"})]}),jsx("b",{children:output(p)}),jsxs("span",{className:"crt-reliability",children:[jsx("b",{children:reliabilityValue(p)??"—"}),jsx("small",{children:reliabilityMeta(p)})]})]}),isExpanded?jsx(CharacterDetail,{player:p}):null]},actorKey);})]})]});
}
