export const PULL_TABLES_QUERY = `
query AvoidPullTables($code:String!,$all:[Int],$best:[Int],$compare:[Int],$p1s:Float,$p1e:Float,$p2s:Float,$p2e:Float,$p3s:Float,$p3e:Float) {
 reportData { report(code:$code, allowUnlisted:true) {
  playerDetails(fightIDs:$all, includeCombatantInfo:true)
  allSummary:table(dataType:Summary,fightIDs:$all)
  allDamageDone:table(dataType:DamageDone,fightIDs:$all)
  allDamageTaken:table(dataType:DamageTaken,fightIDs:$all)
  allHealing:table(dataType:Healing,fightIDs:$all)
  allDeaths:table(dataType:Deaths,fightIDs:$all)
  allInterrupts:table(dataType:Interrupts,fightIDs:$all)
  allDispels:table(dataType:Dispels,fightIDs:$all)
  allBuffs:table(dataType:Buffs,fightIDs:$all)
  allCasts:table(dataType:Casts,fightIDs:$all)
  allDebuffs:table(dataType:Debuffs,fightIDs:$all)
  allSurvivability:table(dataType:Survivability,fightIDs:$all)
  bestSummary:table(dataType:Summary,fightIDs:$best)
  bestDamageDone:table(dataType:DamageDone,fightIDs:$best)
  bestDamageTaken:table(dataType:DamageTaken,fightIDs:$best)
  bestHealing:table(dataType:Healing,fightIDs:$best)
  bestDeaths:table(dataType:Deaths,fightIDs:$best)
  compareSummary:table(dataType:Summary,fightIDs:$compare)
  compareDamageDone:table(dataType:DamageDone,fightIDs:$compare)
  compareHealing:table(dataType:Healing,fightIDs:$compare)
  compareDeaths:table(dataType:Deaths,fightIDs:$compare)
  phase1:table(dataType:Summary,fightIDs:$best,startTime:$p1s,endTime:$p1e)
  phase2:table(dataType:Summary,fightIDs:$best,startTime:$p2s,endTime:$p2e)
  phase3:table(dataType:Summary,fightIDs:$best,startTime:$p3s,endTime:$p3e)
  damageGraph:graph(dataType:DamageDone,fightIDs:$best)
  healingGraph:graph(dataType:Healing,fightIDs:$best)
 } }
}`;
