import { jsx,jsxs } from 'react/jsx-runtime';
import { useEffect,useMemo,useState } from 'react';
import { raidOpsClient } from '../../api/raidOpsClient.js';

const n=value=>Number.isFinite(Number(value))?new Intl.NumberFormat('en-US').format(Number(value)):'—';
const chooseDifficulty=(rows=[],preferred=null)=>preferred&&rows.some(row=>Number(row.id)===Number(preferred))?Number(preferred):Number([...rows].sort((a,b)=>Number(b.id)-Number(a.id))[0]?.id||0)||null;
function sourceCard(label,source,kind,difficulty){let value='NOT AVAILABLE',meta='No persisted source';if(source?.status==='ready'&&kind==='official'){value=`${n(source.spellCount)} SPELLS`;meta=`${n(source.sectionCount)} sections · ${difficulty?.name||'difficulty'} · ${source.difficultyApplicability?.sectionDifficultyMetadataAvailable?'verified':'applicability unresolved'}`;}if(source?.status==='ready'&&kind==='structural'){value=`${n(source.relations)} RELATIONS`;meta=`DB2 ${source.build||'build unknown'} · structural only`;}if(source?.status==='ready'&&kind==='corpus'){value=`${n(source.independentSources)} SOURCES`;meta=`${difficulty?.name||'difficulty'} only · ${n(source.wideReports)} Wide · ${n(source.deepReports)} Deep`;}return jsxs('article',{className:`iris-k-source ${source?.status==='ready'?'ready':'missing'}`,children:[jsx('small',{children:label}),jsx('strong',{children:value}),jsx('p',{children:meta}),jsx('i',{children:source?.status==='ready'?'READY':'MISSING'})]});}
function mechanicCard(mechanic){return jsxs('article',{className:'iris-k-mechanic',children:[jsxs('header',{children:[jsxs('div',{children:[jsx('small',{children:`OBSERVED INVESTIGATION · #${mechanic.anchor.abilityId}`}),jsx('h3',{children:mechanic.anchor.name||`Ability ${mechanic.anchor.abilityId}`})]}),jsx('span',{className:`iris-k-status ${mechanic.status?.tone||'neutral'}`,children:mechanic.status?.label||'UNDER INVESTIGATION'})]}),jsxs('div',{className:'iris-k-stop',children:[jsx('b',{children:'CURRENT EMPIRICAL STATE'}),jsx('p',{children:mechanic.status?.why||'No explanation available.'})]})]},mechanic.episode.id);}
function officialGrid(rows=[]){return rows.length?jsx('div',{className:'iris-k-official-grid',children:rows.map(row=>jsxs('article',{className:'iris-k-official-mechanic',children:[jsxs('header',{children:[jsx('small',{children:row.stage?.name||'OFFICIAL MECHANIC'}),jsx('b',{children:row.name})]}),jsx('div',{children:(row.abilities||[]).map(ability=>jsxs('span',{children:[jsx('b',{children:ability.name||`Spell ${ability.abilityId}`}),jsx('small',{children:`#${ability.abilityId} · ${ability.difficultyApplicability?.status==='explicitly-applicable'?'EXPLICIT':ability.difficultyApplicability?.status==='shared-no-explicit-section-restriction'?'SHARED':'UNRESOLVED'}`})]},ability.abilityId))})]},row.key))}):jsxs('div',{className:'iris-k-empty',children:[jsx('b',{children:'NO OFFICIAL MECHANICS FOR THIS DIFFICULTY'}),jsx('p',{children:'Iris does not borrow mechanics from another difficulty.'})]});}

export function IrisKnowledge(){
  const [catalog,setCatalog]=useState(null),[journal,setJournal]=useState(null),[difficultyId,setDifficultyId]=useState(null),[state,setState]=useState({loading:true,data:null,error:null});
  const raid=catalog?.catalog?.currentRaid||null;
  const boss=useMemo(()=>raid?.encounters?.find(row=>Number(row.journalEncounterId)===Number(journal))||null,[raid,journal]);
  const difficulties=boss?.difficulties||raid?.difficulties||[];
  const difficulty=useMemo(()=>difficulties.find(row=>Number(row.id)===Number(difficultyId))||null,[difficulties,difficultyId]);
  useEffect(()=>{let live=true;raidOpsClient.raidCatalog({official:true}).then(payload=>{if(!live)return;setCatalog(payload);const bosses=payload?.catalog?.currentRaid?.encounters||[],open=window.__AVOID_WCL__?.encounter||{};let selected=bosses.find(row=>row.wclEncounterId&&Number(row.wclEncounterId)===Number(open.id))||bosses[0]||null;setJournal(Number(selected?.journalEncounterId||0)||null);setDifficultyId(chooseDifficulty(selected?.difficulties||payload?.catalog?.currentRaid?.difficulties||[],selected?.wclEncounterId&&Number(selected.wclEncounterId)===Number(open.id)?Number(open.difficulty||0):null));}).catch(error=>{if(live)setState({loading:false,data:null,error:error?.message||String(error)});});return()=>{live=false};},[]);
  useEffect(()=>{if(!boss||!difficultyId)return;let live=true;setState({loading:true,data:null,error:null});raidOpsClient.mechanicKnowledge({encounter:boss.wclEncounterId||undefined,journal:boss.journalEncounterId,difficulty:difficultyId,difficultyName:difficulty?.name,partition:raid?.defaultPartition?.id||0}).then(payload=>{if(live)setState({loading:false,data:payload.result,error:null});}).catch(error=>{if(live)setState({loading:false,data:null,error:error?.message||String(error)});});return()=>{live=false};},[boss?.journalEncounterId,boss?.wclEncounterId,difficultyId,raid?.defaultPartition?.id]);
  if(state.loading&&!catalog)return jsxs('div',{className:'iris-k-loading',children:[jsx('i',{}),jsx('b',{children:'IRIS IS LOADING CURRENT RAID'}),jsx('span',{children:'Boss + difficulty · report optional'})]});
  const selector=raid?jsxs('div',{className:'iris-mechanics-scope',children:[jsxs('div',{className:'iris-k-scope-raid',children:[jsx('small',{children:'CURRENT RAID'}),jsx('b',{children:raid.name}),jsx('span',{children:`${raid.expansion?.name||''} · ${n(raid.encounters?.length)} bosses`})]}),jsxs('label',{children:[jsx('small',{children:'BOSS'}),jsx('select',{value:journal||'',onChange:event=>{const next=Number(event.target.value);setJournal(next);const nextBoss=raid.encounters.find(row=>Number(row.journalEncounterId)===next);setDifficultyId(chooseDifficulty(nextBoss?.difficulties||raid.difficulties||[],null));},children:(raid.encounters||[]).map(row=>jsx('option',{value:row.journalEncounterId,children:row.name},row.journalEncounterId))})]}),jsxs('label',{children:[jsx('small',{children:'DIFFICULTY'}),jsx('select',{value:difficultyId||'',onChange:event=>setDifficultyId(Number(event.target.value)),children:difficulties.map(row=>jsx('option',{value:row.id,children:row.name||`Difficulty ${row.id}`},row.id))})]}),jsxs('div',{className:'iris-k-scope-chip',children:[jsx('small',{children:'KNOWLEDGE SCOPE'}),jsx('b',{children:`${boss?.name||'—'} · ${difficulty?.name||'—'}`}),jsx('span',{children:'Cross-difficulty evidence forbidden'})]})]}):null;
  if(state.error||!state.data)return jsxs('section',{children:[selector,jsxs('div',{className:'iris-k-empty',children:[jsx('b',{children:'IRIS KNOWLEDGE UNAVAILABLE'}),jsx('p',{children:state.error||'No boss+difficulty knowledge is available.'}),jsx('small',{children:'No fallback from another difficulty has been used.'})]})]});
  const data=state.data,sources=data.sources||{},published=data.bossKnowledge?.officialMechanics||[];
  return jsxs('section',{className:'iris-mechanics-knowledge-source',children:[selector,jsxs('div',{className:'iris-k-hero',children:[jsxs('div',{className:'iris-k-eyebrow',children:[jsx('span',{children:'IRIS / BOSS KNOWLEDGE'}),jsx('i',{children:'BOSS + DIFFICULTY · REPORT OPTIONAL'})]}),jsxs('div',{className:'iris-k-title',children:[jsxs('div',{children:[jsx('h2',{children:data.encounter?.name||boss?.name||'Encounter knowledge'}),jsx('p',{children:`${data.difficulty?.name||difficulty?.name||'Difficulty'} is an independent knowledge scope.`})]}),jsx('b',{children:`${n(data.summary?.officialMechanics)} OFFICIAL MECHANICS`})]}),jsxs('div',{className:'iris-k-source-grid',children:[sourceCard('OFFICIAL SEMANTICS',sources.official,'official',data.difficulty||difficulty),sourceCard('SPELL STRUCTURE',sources.structural,'structural',data.difficulty||difficulty),sourceCard('GLOBAL WCL EVIDENCE',sources.corpus,'corpus',data.difficulty||difficulty)]})]}),jsxs('div',{className:'iris-k-section-head',children:[jsxs('div',{children:[jsx('small',{children:`PUBLISHED BOSS MODEL · ${String(data.difficulty?.name||difficulty?.name||'').toUpperCase()}`}),jsx('h3',{children:'Official mechanics'})]}),jsx('p',{children:'No report is required. Difficulty applicability comes from build-pinned Journal metadata when available.'})]}),officialGrid(published),jsxs('div',{className:'iris-k-section-head',children:[jsxs('div',{children:[jsx('small',{children:`IRIS EMPIRICAL LAYER · ${String(data.difficulty?.name||difficulty?.name||'').toUpperCase()}`}),jsx('h3',{children:'Observed relationships'})]}),jsx('p',{children:data.executionKnowledge?.status==='wcl-encounter-not-published'?'WCL encounter ID not published yet.':data.executionKnowledge?.status==='no-combat-corpus-yet'?'No same-difficulty public combat corpus yet; other difficulties are not substituted.':'Same-difficulty public WCL evidence is available.'})]}),jsx('div',{className:'iris-k-mechanics',children:(data.mechanics||[]).length?(data.mechanics||[]).map(mechanicCard):jsxs('div',{className:'iris-k-empty',children:[jsx('b',{children:'NO SAME-DIFFICULTY COMBAT EVIDENCE YET'}),jsx('p',{children:'Official mechanics remain available while Normal, Heroic and Mythic are learned independently.'})]})})]});
}
