import { jsx,jsxs } from 'react/jsx-runtime';
import { useEffect,useMemo,useState } from 'react';
import { raidOpsClient } from '../../api/raidOpsClient.js';

const n=value=>Number.isFinite(Number(value))?new Intl.NumberFormat('en-US').format(Number(value)):'—';
function sourceCard(label,source,kind){let value='NOT AVAILABLE',meta='No persisted source';if(source?.status==='ready'&&kind==='official'){value=`${n(source.spellCount)} SPELLS`;meta=`${n(source.sectionCount)} sections · ${source.namespace||'build unknown'}`;}if(source?.status==='ready'&&kind==='structural'){value=`${n(source.relations)} RELATIONS`;meta=`DB2 ${source.build||'build unknown'}`;}if(source?.status==='ready'&&kind==='corpus'){value=`${n(source.independentSources)} SOURCES`;meta=`${n(source.wideReports)} Wide · ${n(source.deepReports)} Deep`;}return jsxs('article',{className:`iris-k-source ${source?.status==='ready'?'ready':'missing'}`,children:[jsx('small',{children:label}),jsx('strong',{children:value}),jsx('p',{children:meta}),jsx('i',{children:source?.status==='ready'?'READY':'MISSING'})]});}
function mechanicCard(mechanic){return jsxs('article',{className:'iris-k-mechanic',children:[jsxs('header',{children:[jsxs('div',{children:[jsx('small',{children:`OBSERVED MECHANIC INVESTIGATION · #${mechanic.anchor.abilityId}`}),jsx('h3',{children:mechanic.anchor.name||`Ability ${mechanic.anchor.abilityId}`}),jsx('p',{children:mechanic.anchor.officialMembership?.memberships?.[0]?.path?.join(' › ')||'Official membership unresolved'})]}),jsx('span',{className:`iris-k-status ${mechanic.status?.tone||'neutral'}`,children:mechanic.status?.label||'UNDER INVESTIGATION'})]}),jsxs('div',{className:'iris-k-stop',children:[jsx('b',{children:'CURRENT EMPIRICAL STATE'}),jsx('p',{children:mechanic.status?.why||'No explanation available.'})]}),jsx('div',{className:'iris-k-ladder',children:(mechanic.evidenceLadder||[]).map(row=>jsxs('div',{className:`iris-k-stage ${row.tone||'neutral'}`,children:[jsx('span',{children:row.label}),jsx('b',{children:String(row.status||'—').replaceAll('-',' ').toUpperCase()}),jsx('small',{children:row.detail||''})]},row.code))})]},mechanic.episode.id);}
function officialGrid(rows=[]){return rows.length?jsx('div',{className:'iris-k-official-grid',children:rows.map(row=>jsxs('article',{className:'iris-k-official-mechanic',children:[jsxs('header',{children:[jsx('small',{children:row.stage?.name||'OFFICIAL MECHANIC'}),jsx('b',{children:row.name})]}),jsx('div',{children:(row.abilities||[]).map(ability=>jsxs('span',{children:[jsx('b',{children:ability.name||`Spell ${ability.abilityId}`}),jsx('small',{children:`#${ability.abilityId}`})]},ability.abilityId))})]},row.key))}):jsxs('div',{className:'iris-k-empty',children:[jsx('b',{children:'OFFICIAL JOURNAL NOT AVAILABLE YET'}),jsx('p',{children:'Iris will not infer boss mechanics from combat logs when official metadata is absent.'})]});}

export function IrisKnowledge(){
  const [catalog,setCatalog]=useState(null),[selected,setSelected]=useState(null),[state,setState]=useState({loading:true,data:null,error:null});
  const raid=catalog?.catalog?.currentRaid||null;
  const boss=useMemo(()=>raid?.encounters?.find(row=>Number(row.wclEncounterId)===Number(selected))||null,[raid,selected]);
  useEffect(()=>{let live=true;raidOpsClient.raidCatalog({official:true}).then(payload=>{if(!live)return;setCatalog(payload);const bosses=payload?.catalog?.currentRaid?.encounters||[],reportId=Number(window.__AVOID_WCL__?.encounter?.id||0);setSelected((reportId&&bosses.some(row=>Number(row.wclEncounterId)===reportId))?reportId:Number(bosses[0]?.wclEncounterId||0)||null);}).catch(error=>{if(live)setState({loading:false,data:null,error:error?.message||String(error)});});return()=>{live=false};},[]);
  useEffect(()=>{if(!boss)return;let live=true;setState({loading:true,data:null,error:null});raidOpsClient.mechanicKnowledge({encounter:boss.wclEncounterId,difficulty:5,partition:raid?.defaultPartition?.id||0}).then(payload=>{if(live)setState({loading:false,data:payload.result,error:null});}).catch(error=>{if(live)setState({loading:false,data:null,error:error?.message||String(error)});});return()=>{live=false};},[boss?.wclEncounterId,raid?.defaultPartition?.id]);
  if(state.loading&&!catalog)return jsxs('div',{className:'iris-k-loading',children:[jsx('i',{}),jsx('b',{children:'IRIS IS LOADING CURRENT RAID'}),jsx('span',{children:'WorldData + Blizzard Journal · combat report optional'})]});
  const selector=raid?jsxs('div',{className:'iris-k-raid-scope',children:[jsxs('div',{children:[jsx('small',{children:'CURRENT RAID'}),jsx('b',{children:raid.name}),jsx('span',{children:`${raid.expansion?.name||''} · ${raid.frozen?'FROZEN':'ACTIVE'} · ${n(raid.encounters?.length)} bosses`})]}),jsxs('label',{children:[jsx('small',{children:'BOSS'}),jsx('select',{value:selected||'',onChange:event=>setSelected(Number(event.target.value)),children:(raid.encounters||[]).map(row=>jsx('option',{value:row.wclEncounterId,children:row.name},row.wclEncounterId))})]})]}):null;
  if(state.error||!state.data)return jsxs('section',{children:[selector,jsxs('div',{className:'iris-k-empty',children:[jsx('b',{children:'IRIS KNOWLEDGE UNAVAILABLE'}),jsx('p',{children:state.error||'No official or empirical boss knowledge is available.'}),jsx('small',{children:'No fallback data has been invented.'})]})]});
  const data=state.data,sources=data.sources||{},published=data.bossKnowledge?.officialMechanics||[];
  return jsxs('section',{className:'iris-mechanics-knowledge-source',children:[selector,jsxs('div',{className:'iris-k-hero',children:[jsxs('div',{className:'iris-k-eyebrow',children:[jsx('span',{children:'IRIS / BOSS KNOWLEDGE'}),jsx('i',{children:'OFFICIAL FIRST · REPORT OPTIONAL'})]}),jsxs('div',{className:'iris-k-title',children:[jsxs('div',{children:[jsx('h2',{children:data.encounter?.name||boss?.name||'Encounter knowledge'}),jsx('p',{children:'Official boss model is independent of reports; empirical evidence attaches later.'})]}),jsx('b',{children:`${n(data.summary?.officialMechanics)} OFFICIAL MECHANICS`})]}),jsxs('div',{className:'iris-k-source-grid',children:[sourceCard('OFFICIAL SEMANTICS',sources.official,'official'),sourceCard('SPELL STRUCTURE',sources.structural,'structural'),sourceCard('GLOBAL WCL EVIDENCE',sources.corpus,'corpus')]})]}),jsxs('div',{className:'iris-k-section-head',children:[jsxs('div',{children:[jsx('small',{children:'PUBLISHED BOSS MODEL'}),jsx('h3',{children:'Official mechanics'})]}),jsx('p',{children:'Blizzard Journal hierarchy and abilities. No report is required.'})]}),officialGrid(published),jsxs('div',{className:'iris-k-section-head',children:[jsxs('div',{children:[jsx('small',{children:'IRIS EMPIRICAL LAYER'}),jsx('h3',{children:'Observed relationships'})]}),jsx('p',{children:data.executionKnowledge?.status==='no-combat-corpus-yet'?'No public combat corpus yet; this is expected during a new tier/RWF embargo.':'Public WCL evidence is available and remains separate from official semantics.'})]}),jsx('div',{className:'iris-k-mechanics',children:(data.mechanics||[]).length?(data.mechanics||[]).map(mechanicCard):jsxs('div',{className:'iris-k-empty',children:[jsx('b',{children:'NO COMBAT EVIDENCE YET'}),jsx('p',{children:'Official mechanics remain available. Global WCL and AvoiD execution will attach when reports become available.'})]})})]});
}
