import { spawnSync } from 'node:child_process';
import { access, readFile } from 'node:fs/promises';
import process from 'node:process';

const files = [
  'workflows/corpus-build.js','scripts/iris-local-worker.mjs','scripts/iris-raid-catalog-smoke.mjs','scripts/iris-official-encounter-smoke.mjs','scripts/iris-spell-structure-smoke.mjs','scripts/iris-evidence-groups-smoke.mjs','scripts/iris-untouched-holdout-smoke.mjs',
  'routes/api/wcl/report.js','routes/api/wcl/telemetry.js','routes/api/wcl/history.js','routes/api/wcl/intelligence.js','routes/api/wcl/status.js','routes/api/wcl/corpus.js','routes/api/wcl/semantic-probe.js','routes/api/wcl/semantic-actor-provenance.js','routes/api/wcl/mechanic-episode.js','routes/api/wcl/matched-null-baseline.js','routes/api/wcl/evidence-groups.js','routes/api/wcl/statistical-stability.js','routes/api/wcl/untouched-holdout.js','routes/api/wcl/mechanic-knowledge.js','routes/api/wcl/reports.js','routes/api/knowledge.js','routes/api/knowledge/ability.js','routes/api/knowledge/encounter.js','routes/api/knowledge/spell-structure.js','routes/api/knowledge/raid-catalog.js','routes/api/iris/capabilities.js','routes/api/iris/sources.js',
  'server/wcl/auth/token-cache.mjs','server/wcl/client/graphql-client.mjs','server/wcl/queries/raid-catalog.mjs','server/wcl/queries/telemetry.mjs','server/wcl/queries/report-catalog.mjs','server/wcl/queries/semantic-probes.mjs','server/wcl/queries/semantic-actor-provenance.mjs','server/wcl/queries/ability-knowledge.mjs','server/wcl/normalization/events.mjs',
  'server/corpus/storage.mjs','server/corpus/execution.mjs','server/corpus/model-policy-v373.mjs','server/corpus/model-policy-v374.mjs','server/corpus/model-policy-v375.mjs','server/corpus/model-policy-v376.mjs','server/corpus/model-policy-v377.mjs','server/corpus/model-policy-v378.mjs','server/corpus/model-policy-v379.mjs','server/corpus/model-policy-v380.mjs','server/corpus/query-guided-deep-v1.mjs','server/corpus/targeted-deep-v373.mjs','server/corpus/surgical-probe-planner-v1.mjs','server/corpus/semantic-surgical-probe-planner-v1.mjs','server/corpus/semantic-surgical-probe-planner-v2.mjs','server/corpus/semantic-surgical-probe-executor-v1.mjs','server/corpus/semantic-probe-wcl-v1.mjs','server/corpus/semantic-probe-verifier-v1.mjs','server/corpus/semantic-probe-verifier-v2.mjs','server/corpus/semantic-probe-verifier-v3.mjs','server/corpus/semantic-probe-stored-evidence-v2.mjs','server/corpus/semantic-actor-provenance-v1.mjs','server/corpus/mechanic-episode-graph-v1.mjs','server/corpus/mechanic-episode-official-reconciliation-v1.mjs','server/corpus/mechanic-episode-structural-reconciliation-v1.mjs','server/corpus/mechanic-knowledge-view-v1.mjs','server/corpus/matched-null-baseline-v1.mjs','server/corpus/matched-null-baseline-executor-v1.mjs','server/corpus/independent-evidence-groups-v1.mjs','server/corpus/statistical-stability-v1.mjs','server/corpus/untouched-holdout-v1.mjs','server/corpus/untouched-holdout-source-pool-v1.mjs','server/corpus/untouched-holdout-source-discovery-v1.mjs','server/corpus/untouched-holdout-acquisition-v1.mjs','server/corpus/local-mechanic-synthesis-v1.mjs','server/corpus/deep-events-pagination.mjs','server/corpus/deep-profile-v373.mjs','server/corpus/corpus-step-v373.mjs','server/corpus/corpus-step-v375.mjs','server/corpus/corpus-step-v376.mjs','server/corpus/sampling-v2.mjs','server/corpus/canonical-rebuild-v2.mjs','server/corpus/service-v2.mjs',
  'server/knowledge/scopes.mjs','server/knowledge/keys.mjs','server/knowledge/raid-ledger.mjs','server/knowledge/raid-catalog-v1.mjs','server/knowledge/raid-catalog-store-v1.mjs','server/knowledge/raid-official-bootstrap-v1.mjs','server/knowledge/game-knowledge-v1.mjs','server/knowledge/knowledge-store-v1.mjs','server/knowledge/ability-knowledge-v1.mjs','server/knowledge/official-encounter-knowledge-v1.mjs','server/knowledge/official-encounter-store-v1.mjs','server/knowledge/official-encounter-reconciliation-v1.mjs','server/knowledge/spell-relation-graph-v1.mjs','server/knowledge/spell-structural-knowledge-v1.mjs','server/knowledge/spell-structural-store-v1.mjs','server/knowledge/providers/blizzard-game-data-v1.mjs','server/knowledge/providers/wago-db2-spell-effect-v1.mjs','server/knowledge/providers/lorrgs-client-v1.mjs','server/knowledge/providers/parse-wowhead-client-v1.mjs','server/knowledge/providers/wcl-static-metadata-v1.mjs','server/iris/capability-contract-v390.mjs','server/iris/capability-contract-v3910.mjs','server/iris/external-source-registry-v390.mjs',
  'server/analysis/progression/raid-sessions.mjs','server/analysis/progression/progress-metrics-v1.mjs','server/analysis/progression/progress-metric-registry-v1.mjs','server/analysis/progression/progress-metrics-v2.mjs','server/analysis/progression/progress-metric-registry-v2.mjs','server/analysis/reliability/reliability-policy-v1.mjs','server/analysis/reliability/reliability-metric-registry-v1.mjs','server/analysis/reliability/evidence-contracts-v1.mjs','server/analysis/reliability/evidence-ledger-v1.mjs','server/analysis/reliability/peer-baseline-v1.mjs','server/analysis/reliability/reliability-engine-v1.mjs','server/analysis/reliability/attendance-history-v1.mjs',
  'server/engines/history-engine.mjs','server/engines/intelligence-engine.mjs','server/engines/report-catalog-engine.mjs','server/services/report-catalog-service.mjs','server/services/knowledge-service.mjs','server/services/ability-knowledge-service.mjs','server/services/official-encounter-knowledge-service.mjs','server/services/spell-structural-knowledge-service.mjs','server/services/mechanic-knowledge-view-service.mjs','server/services/iris-capabilities-service.mjs','server/services/iris-sources-service.mjs','server/corpus/wide-profile.mjs','server/corpus/source-expansion.mjs',
  'public/wcl-bootstrap-v389.js','public/data-hub-v390.js','public/knowledge-reindex-v390.js','public/iris-runtime-v3713.js','public/iris-mechanics-knowledge-v3910.js','public/progress-runtime-v3713.js','public/encounter-intelligence-v375.js','public/corpus-ui-stability-v1.js','public/player-intelligence-v392.js'
];

let failures = 0;
for (const file of files) {
  try { await access(file); }
  catch { console.error(`[verify:vercel] MISSING ${file}`); failures++; continue; }
  const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8'});
  if(result.status===0){console.log(`[verify:vercel] OK      ${file}`);continue;}
  failures++;console.error(`[verify:vercel] SYNTAX  ${file}`);if(result.stdout)process.stderr.write(result.stdout);if(result.stderr)process.stderr.write(result.stderr);
}
try{const vercel=JSON.parse(await readFile('vercel.json','utf8'));const deployment=vercel?.git?.deploymentEnabled||{};if(deployment.main!==true||deployment['*']!==false)throw new Error('vercel.json must deploy main only and disable branch previews');console.log('[verify:vercel] OK      vercel.json main-only deployment contract');}catch(error){failures++;console.error(`[verify:vercel] CONTRACT vercel.json: ${error?.message||error}`);}
try{
  const pkg=JSON.parse(await readFile('package.json','utf8'));
  if(pkg?.engines?.node!=='22.x')throw new Error('package.json engines.node must remain 22.x');
  if(pkg?.dependencies?.workflow!=='5.0.0-beta.36')throw new Error('workflow dependency pin changed');
  if(pkg?.dependencies?.nitro!=='3.0.260610-beta')throw new Error('nitro dependency pin changed');
  if(pkg?.dependencies?.['@vercel/blob']!=='2.6.1')throw new Error('@vercel/blob dependency pin changed');
  if(pkg?.scripts?.['test:critical']!=='node --test tests/critical/*.test.mjs')throw new Error('critical test gate missing');
  if(pkg?.scripts?.['validate:raid-catalog']!=='node --env-file=.env.local scripts/iris-raid-catalog-smoke.mjs')throw new Error('raid catalog smoke command missing');
  if(pkg?.scripts?.['validate:spell-structure']!=='node --env-file=.env.local scripts/iris-spell-structure-smoke.mjs')throw new Error('spell structural smoke command missing');
  if(pkg?.scripts?.['validate:evidence-groups']!=='node --env-file=.env.local scripts/iris-evidence-groups-smoke.mjs')throw new Error('evidence groups/stability smoke command missing');
  if(pkg?.scripts?.['validate:untouched-holdout']!=='node --env-file=.env.local scripts/iris-untouched-holdout-smoke.mjs')throw new Error('untouched holdout smoke command missing');
  if(!String(pkg?.scripts?.build||'').includes('test:critical'))throw new Error('build must run critical tests');
  console.log('[verify:vercel] OK      package runtime pins + critical test gate');
}catch(error){failures++;console.error(`[verify:vercel] CONTRACT package.json: ${error?.message||error}`);}
if(failures){console.error(`[verify:vercel] FAILED · ${failures} problem${failures===1?'':'s'}`);process.exit(1);}console.log(`[verify:vercel] PASS · ${files.length} syntax checks + deployment contracts`);
