import test from 'node:test';
import assert from 'node:assert/strict';
import { applyEncounterPolicyV373 } from '../../server/corpus/model-policy-v373.mjs';
import { attachOriginEvidenceV373 } from '../../server/corpus/deep-profile-v373.mjs';
import { prioritizeWideProfilesForDeepV373 } from '../../server/corpus/targeted-deep-v373.mjs';

const metric=(reportsWith=0)=>({reportsWith,count:reportsWith,total:reportsWith});
function ability(id,name,{aura=0,damage=0,cast=0}={}){const cohort={Casts:metric(cast),Damage:metric(damage),Buffs:metric(aura),Debuffs:metric(aura)};return{id,name,wide:{kill:structuredClone(cohort),wipe:structuredClone(cohort)},deep:{kill:{},wipe:{}},stateAlignment:{}};}
const dim={key:'feather',tokenGroup:'light-void',values:{LIGHT:{ids:[1241162]},VOID:{ids:[1241163]}},confidence:1,source:'mirrored-aura-family',evidence:{auraScore:1,balance:1}};
const mech=(id,name,value,validation=.9,inference='stateful-impact-observed')=>({key:`m-${id}`,name,category:'assignment',severity:4,requiredState:{dimension:'feather',value},stateValueIds:[value==='LIGHT'?1241162:1241163],scoreable:false,inference,damageIds:inference==='stateful-cast-observed'?[]:[id],castIds:inference==='stateful-cast-observed'?[id]:[],generated:{primaryAbilityId:id,semanticWeight:1.2,trainingConfidence:.9,validationScore:validation,stateTokenGroup:'light-void'}});

function fixture(){
  const abilities={};const add=(id,name,a)=>abilities[String(id)]=ability(id,name,a);
  add(1241162,'Light Feather',{aura:90});add(1241163,'Void Feather',{aura:90});
  add(1241291,'Light Dive',{damage:80,cast:80});add(1241340,'Void Dive',{damage:80,cast:80});
  add(1241646,'Light Edict',{damage:75});add(1241676,'Void Edict',{damage:75});
  add(1261217,'Light Edict',{cast:45});add(1261218,'Void Edict',{cast:45});
  add(1242991,'Light Echo',{damage:80});add(1242996,'Void Echo',{damage:80});add(77489,'Echo of Light',{aura:60});
  add(448005,'Light of the Martyr',{damage:50,aura:50});add(1287955,'Rune of Void-Tainted Shell',{aura:50});
  add(1260826,"Guardian's Edict",{damage:40});add(1263412,'Rebirth',{cast:55});
  const train={wideReports:102,deepReports:20,killReports:40,wipeReports:62,killPulls:100,wipePulls:600,deepKillPulls:20,deepWipePulls:120,abilities,statePairs:{},relations:{castToEnemyAura:{},castToDamage:{}},sourceReports:{},originEvidence:{'77489':{friendlySourceEvents:32,encounterOrUnknownSourceEvents:0,unknownSourceEvents:0,reportsWithEvidence:4},'1261217':{friendlySourceEvents:0,encounterOrUnknownSourceEvents:24,unknownSourceEvents:0,reportsWithEvidence:4}}};
  const mechanics=[mech(1241291,'Light Dive','LIGHT'),mech(1241340,'Void Dive','VOID'),mech(1241646,'Light Edict','LIGHT'),mech(1241676,'Void Edict','VOID'),mech(1261217,'Light Edict','LIGHT',.95,'stateful-cast-observed'),mech(1261218,'Void Edict','VOID',.95,'stateful-cast-observed'),mech(1242991,'Light Echo','LIGHT'),mech(1242996,'Void Echo','VOID'),mech(448005,'Light of the Martyr','LIGHT'),mech(1287955,'Rune of Void-Tainted Shell','VOID'),{key:'rebirth',name:'Rebirth',category:'dangerous-cast',scoreable:true,inference:'completed-cast-is-failure',castIds:[1263412],generated:{primaryAbilityId:1263412,semanticWeight:1.6,trainingConfidence:1,validationScore:.82}}];
  const model={schemaVersion:3,engineVersion:'3.7.1',status:'candidate',encounterId:3182,difficulty:5,partition:4,resolvedPartition:4,generatedAt:1,corpus:{wideReports:136,deepReports:26,killPulls:139,wipePulls:870,deepKillPulls:28,deepWipePulls:175,independentSources:136,validationSources:34,validationReports:34},validation:{acceptedMechanics:mechanics.length,rejectedMechanics:2,meanScore:.9,publishChecks:{},thresholds:{minWideReports:250,minDeepReports:50,minWidePulls:2500,minDeepPulls:300,minIndependentSources:50,minValidationSources:12,minValidationReports:50,minMeanScore:.66,minLearnedPct:82,minSemanticCoverage:.7,minSignalCoverage:.75,maxCriticalUnresolved:0}},learning:{scorePct:70,components:{dataDepthPct:55.5,holdoutPct:83.3,signalCoveragePct:80,semanticResolutionPct:70,diversityPct:100},criticalUnresolvedSignals:[]},discovery:{stateDimensions:[dim],variantFamilies:[],relationCandidates:[]},pack:{id:3182,name:"Belo'ren",stateDimensions:[dim],mechanics},rejected:[{key:'guardian',name:"Guardian's Edict",primaryAbilityId:1260826,trainingConfidence:.63,validationScore:.79,reason:'training-confidence'},{key:'martyr-filter',name:'Light of the Martyr',primaryAbilityId:448005,inference:'encounter-origin-filter',reason:'encounter-origin-policy'}]};
  return{model,aggregate:{wideReports:136,deepReports:26,killPulls:139,wipePulls:870,deepKillPulls:28,deepWipePulls:175,splits:{train,validation:{...train,wideReports:34}},sourceReports:{}}};
}

test('v3.7.3 separates lexical members from encounter-facing members',()=>{const {model,aggregate}=fixture(),out=applyEncounterPolicyV373(model,aggregate),echo=out.discovery.variantFamilies.find(f=>f.key==='light-void:echo');assert.ok(echo);assert.ok(echo.lexicalMemberIds.includes(77489));assert.ok(!echo.encounterMemberIds.includes(77489));assert.ok(echo.encounterMemberIds.includes(1242991));assert.ok(echo.encounterMemberIds.includes(1242996));});

test('v3.7.3 keeps secondary enemy-cast Edict members while filtered player/item signals stay out',()=>{const {model,aggregate}=fixture(),out=applyEncounterPolicyV373(model,aggregate),ids=new Set(out.pack.mechanics.map(m=>m.generated?.primaryAbilityId));assert.ok(ids.has(1261217));assert.ok(ids.has(1261218));assert.ok(!ids.has(448005));assert.ok(!ids.has(1287955));assert.equal(out.policyVersion,'encounter-origin-v3');});

test('v3.7.3 enrichment focus never includes origin-filtered signals',()=>{const {model,aggregate}=fixture(),out=applyEncounterPolicyV373(model,aggregate),focus=new Set(out.learning.enrichmentFocusAbilityIds);assert.ok(focus.has(1260826));assert.ok(!focus.has(448005));assert.ok(!focus.has(1287955));assert.equal(out.learning.enrichmentRecommendation.suggestedAdditionalWidePulls,0);});

test('v3.7.3 separates lowest score from actionable bottleneck',()=>{const {model,aggregate}=fixture(),out=applyEncounterPolicyV373(model,aggregate);assert.ok(out.learning.lowestDimension);assert.equal(out.learning.actionBottleneck,'relationUnderstandingPct');assert.equal(out.learning.bottleneck,out.learning.actionBottleneck);});

test('origin evidence classifies friendly vs encounter-or-unknown sources without pretending hostility',()=>{const profile={schemaVersion:3,fights:[{id:1,startTime:0,endTime:10000,friendlyPlayers:[10,11]}],completeness:{enemyCasts:true,friendDamage:true,debuffs:true,buffs:true,enemyBuffs:true,enemyDebuffs:true}},data={reportData:{report:{enemyCasts:{data:[{fight:1,timestamp:100,type:'cast',abilityGameID:500,sourceID:90}]},friendDamage:{data:[{fight:1,timestamp:200,type:'damage',abilityGameID:600,sourceID:10},{fight:1,timestamp:300,type:'damage',abilityGameID:601,sourceID:91}]},debuffs:{data:[]},buffs:{data:[]},enemyBuffs:{data:[]},enemyDebuffs:{data:[]}}}};attachOriginEvidenceV373(profile,data);assert.equal(profile.originEvidence['500'].encounterOrUnknownSourceEvents,1);assert.equal(profile.originEvidence['600'].friendlySourceEvents,1);assert.equal(profile.originEvidence['601'].encounterOrUnknownSourceEvents,1);assert.equal(profile.originEvidenceVersion,'friendly-vs-encounter-or-unknown-v1');});

test('targeted Deep prioritization still favors focus abilities without losing source variety',()=>{const p=(code,guild,focus,best)=>({code,guild:{id:guild},kills:0,wipes:3,fights:[{fightPercentage:best}],tables:{wipeDamage:focus?{'1260826':{count:3}}:{}}});const rows=prioritizeWideProfilesForDeepV373([p('A',1,false,30),p('B',2,true,60),p('C',3,true,20),p('D',2,true,10)],[],[1260826]);assert.equal(rows[0].__focus,1);assert.ok(new Set(rows.slice(0,3).map(x=>x.__source)).size>=2);});
